### ISSUE TITLE
RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated

### ISSUE THREAD

**Issue by ashleylid** [shzygmyx/Matrix-Capsules-pytorch#4]
Hi, 
I am on windows 10 with python 3 and conda install. I have just cloned and ran as suggested and I get this error RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated. Is this something you may have seen? 
Thanks.

**Comment by YuxianMeng** [comment]
I didn't see this error. I'm using pytorch 0.3, so this problem may occur in pytorch 0.4 or 1.0? @kleinash

**Comment by ashleylid** [comment]
Perhaps, I managed to get it working on Linux - haven't tried again with windows.
